name: CI/CD Build Docker image and push to Docker hub and Deploy in AWS EC2

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: priyanjithn/cinehub-backend:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
        
      - name: Run command on EC2 instance
        uses: actions/ssh-key-action@v1
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            sudo docker stop cinehub-backend
            sudo docker rm cinehub-backend
            sudo docker rmi priyanjithn/cinehub-backend:latest
            sudo docker pull priyanjithn/cinehub-backend:latest
            sudo docker run -d --name cinehub-backend -p 8080:8080 --env-file .env priyanjithn/cinehub-backend
