name: CI/CD Build Docker image and push to Docker hub and Deploy in AWS EC2

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: priyanjithn/cinehub-backend:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Pull Docker image and run container
        run: |
          ssh -T -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker stop cinehub-backend
            sudo docker rm cinehub-backend
            sudo docker rmi priyanjithn/cinehub-backend:latest
            sudo docker pull priyanjithn/cinehub-backend:latest
            sudo docker run -d --name cinehub-backend -p 8080:8080 --env-file .env priyanjithn/cinehub-backend
          EOF
